- name: Configure Vim
  hosts: all
  vars:
      vim_dir: "{{ ansible_env.HOME }}/.vim"
  tasks:
      - name: Vim configuration files are present.
        file:
            src: "{{ playbook_dir }}"
            dest: "{{ vim_dir }}"
            state: link

      - name: Package dependencies are installed.
        package:
            name:
              - eslint
              - fzf
              - git
              - prettier
              - python-pip
              - python-pynvim
              - python-black
              - the_silver_searcher
              - typescript
            state: present
        become: true
