- name: Configure Vim
  hosts: all
  vars:
      vim_dir: "{{ ansible_env.HOME }}/.vim"
  tasks:
      - name: Vim configuration files are present.
        file:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
            state: link
        with_items:
            - src: "{{ playbook_dir }}"
              dest: "{{ vim_dir }}"
            - src: "{{ playbook_dir }}/vimrc"
              dest: "{{ ansible_env.HOME }}/.vimrc"

      - name: Package dependencies are installed.
        package:
            name: git
            state: present
